// <auto-generated />
using AntiPsychRRMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntiPsychRRMVC.Migrations
{
    [DbContext(typeof(AntiPsychRRMVCContext))]
    partial class AntiPsychRRMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AntiPsychRRMVC2.Models.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"), 1L, 1);

                    b.Property<int>("DrugFrequencyID")
                        .HasColumnType("int");

                    b.Property<int>("DrugMaxDoseID")
                        .HasColumnType("int");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrugRouteID")
                        .HasColumnType("int");

                    b.HasKey("DrugId");

                    b.ToTable("Drug");
                });
#pragma warning restore 612, 618
        }
    }
}
